# Generated by Django 3.2.3 on 2021-05-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_ranking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('d_score', models.IntegerField(default=0)),
                ('information', models.CharField(max_length=128)),
            ],
        ),
    ]
